### ISSUE TITLE
Regarding branch 8080-arvbox docker box

### ISSUE THREAD

**Issue by brainstorm** [curoverse/arvados-dev#4]
@tetron, why does the `./arvbox build dev` and `./arvbox start dev` does not pull a readily installed arvados box instead of pulling a minimal installation and then installing all ruby/python/etc modules:

```
Waiting for workbench api doc sso keepstore0 keepstore1 keepproxy sdk (installing ruby gems 59/277) ...
Waiting for workbench api doc sso keepstore0 keepstore1 keepproxy sdk (installing ruby gems 59/277) ...
Waiting for workbench api doc sso keepstore0 keepstore1 keepproxy sdk (installing ruby gems 59/277) ...
Waiting for workbench api doc sso keepstore0 keepstore1 keepproxy sdk (installing ruby gems 59/277) ...
Waiting for workbench api doc sso keepstore0 keepstore1 keepproxy sdk (installing ruby gems 59/277) ...
```

Having to wait (as mentioned during the install) for 10-15 minutes?

Thanks @guillermo-carrasco for raising this issue in a discussion about the new `arvbox` deployment mechanism.

**Comment by tetron** [comment]
Hi @brainstorm,

There is another build, "arvbox build demo" which does construct a docker image with packages pre-installed.

The difference between the "dev" and "demo" builds is that the "dev" build is intended to be used by developers who need to modify Arvados (including such things as updating Ruby and Python package dependencies) so the directories containing code and stateful data are bind-mounted from the host file system.  The "demo" build is more self-contained with the code and data contained entirely in containers.

I should probably further improve the documentation to explain the difference and possibly recommend the "demo" build and not the "dev" build by default.

We intend to publish Docker images which you can pull (instead of having to build the images yourself) but because arvbox is pretty new we haven't hooked up the infrastructure yet.

**Comment by brainstorm** [comment]
You just did in the last commits, thanks! :+1:
